[package]
name = "homelander"
version = "0.1.0"
edition = "2021"

[dependencies]
thiserror = "1.0.31"
tracing = "0.1.35"
strum_macros = "0.24.2"
convert_case = "0.5.0"
dyn-clone = "1.0.8"

[dependencies.serde]
version = "1.0"
features = ["derive"]

[dev-dependencies]
serde_json = "1.0"