[package]
name = "homelander"
version = "0.1.0"
edition = "2021"

[dependencies]
thiserror = "1.0.31"
tracing = "0.1.35"

[dependencies.serde]
version = "1.0"
features = ["derive"]

[dev-dependencies]
serde_json = "1.0"